FROM amazonlinux:2023
# Maintainer information
LABEL maintainer="Ilya Rokhkin"

# Update system and install common tools
RUN dnf update -y && \
    dnf install -y \
    epel-release \
    sos \
    crash \
    ltrace \
    abrt \
    pcp \
    systemtap \
    perf \
    bc \
    blktrace \
    btrfs-progs \
    hwloc \
    iotop \
    pciutils \
    mailx \
    man-db \
    net-tools \
    numactl \
    passwd \
    psmisc \
    screen \
    sysstat \
    traceroute \
    lynx \
    unzip \
    tmux \
    bind-utils \
    jq && \
    dnf clean all


# Install Python3 and pip
RUN dnf install -y python3-pip

# Upgrade pip and install Python modules
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install pyyaml redis

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install && rm -f awscliv2.zip

# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip && \
    unzip terraform_1.0.8_linux_amd64.zip -d /usr/local/bin/ && \
    rm terraform_1.0.8_linux_amd64.zip

# Install Go
RUN wget https://golang.org/dl/go1.17.2.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.17.2.linux-amd64.tar.gz && \
    rm go1.17.2.linux-amd64.tar.gz

# Install Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm -f kubectl

# Install Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Clean up to reduce image size
RUN dnf clean all && rm -rf /var/cache/dnf

USER root

# Default entrypoint
ENTRYPOINT [ "/bin/bash" ]
