FROM centos:centos7

MAINTAINER The CentOS Project <cloud-ops@centos.org> https://hub.docker.com/r/centos/tools/dockerfile

LABEL maintainer="Ilya Rokhkin"

ENV container docker
LABEL RUN="docker run -it --name NAME --privileged --ipc=host --net=host --pid=host -e HOST=/host -e NAME=NAME -e IMAGE=IMAGE -v /sys/fs/selinux:/sys/fs/selinux:ro -v /run:/run -v /var/log:/var/log -v /etc/localtime:/etc/localtime -v /:/host IMAGE"

RUN [ -e /etc/yum.conf ] && sed -i '/tsflags=nodocs/d' /etc/yum.conf || true

# Reinstall all packages to get man pages for them
RUN yum -y reinstall "*" && yum clean all

# install common tools
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum update -y

# Swap out the systemd-container package and install all useful packages
RUN yum -y install \
           kernel \
           e2fsprogs \
           sos \
           crash \
           strace \
           ltrace \
           tcpdump \
           abrt \
           pcp \
           systemtap \
           perf \
           bc \
           blktrace \
           btrfs-progs \
           ethtool \
           file \
           findutils \
           gcc \
           gdb \
           git \
           glibc-common \
           glibc-utils \
           hwloc \
           iotop \
           iproute \
           iputils \
           less \
           pciutils \
           ltrace \
           mailx \
           man-db \
           nc \
           netsniff-ng \
           net-tools \
           numactl \
           numactl-devel \
           passwd \
           perf \
           procps-ng \
           psmisc \
           screen \
           strace \
           sysstat \
           systemtap-client \
           tar \
           tcpdump \
           vim-enhanced \
           xauth \
           which \
           ostree \
           rpm-ostree \
           docker \
           python-docker-py \
           docker-selinux \
           kubernetes-client \
           kubernetes-node \
           kubernetes-devel \
           kubernetes-master \
           gdb-gdbserver \
           vim-minimal \
           bash-completion \
           subscription-manager \
           python-rhsm \
           rootfiles \
           yum-utils \

## Install Devops tools
RUN yum install -y sudo \
		   bash \
		   curl \
		   wget \
		   nano \
		   vim \
		   tmux \
		   gcc \
		   gcc-c++ \
		   make \
		   unzip \
        	   python3-pip \
		   meld \
		   nodejs \

## clean all to clean space
RUN yum clean all

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install pyyaml
RUN python3 -m pip install redis

RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo
RUN export release=AmazonLinux
RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/$release/hashicorp.repo
RUN yum install terraform


# Set default command
CMD ["/usr/bin/bash"]
