name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: 
      - 'v*'  # This will trigger the workflow for any tag that starts with v

jobs:
  build:
    runs-on: ubuntu-latest  # Lightweight OS for Docker builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gfish/devenv_amazonlinux_2023:latest
          platforms: linux/amd64,linux/arm64  # Specify target platforms
