name: Create Docker Image Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v0.0.1)'
        required: true
      docker_tags:
        description: 'Docker image references (comma-separated, format: namespace/repository)'
        required: true

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Fetch Docker Image Details
        id: fetch-details
        run: |
          {
            echo 'RELEASE_BODY<<EOF'
            echo "# Docker Images for Release ${{ github.event.inputs.version }}"
            echo ""
            
            IFS=',' read -ra IMAGES <<< "${{ github.event.inputs.docker_tags }}"
            for image in "${IMAGES[@]}"; do
              image=$(echo "$image" | xargs)
              echo "Fetching details for $image..."
              
              TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_PASSWORD }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
              
              NAMESPACE=$(echo $image | cut -d'/' -f1)
              REPOSITORY=$(echo $image | cut -d'/' -f2)
              VERSION="${{ github.event.inputs.version }}"
              
              # Fetch repository info
              REPO_INFO=$(curl -s -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/${NAMESPACE}/${REPOSITORY}/")
              
              # Fetch specific tag info
              TAG_INFO=$(curl -s -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/${NAMESPACE}/${REPOSITORY}/tags/${VERSION}/")
              
              echo "Debug: Full Tag Info for ${image}"
              echo "$TAG_INFO" | jq '.'
              
              DESCRIPTION=$(echo $REPO_INFO | jq -r '.description // "No description available"')
              LAST_UPDATED=$(echo $TAG_INFO | jq -r '.last_updated // "Unknown"')
              SIZE=$(echo $TAG_INFO | jq -r '.full_size // "0"')
              
              # Get architectures with improved detection
              ARCHITECTURES=$(echo $TAG_INFO | jq -r '.images[] | . as $img | 
                if ($img.architecture == "arm64") or ($img.os_arch == "arm64") then
                  "\n- **ARM64:** `" + $img.digest + "`"
                elif ($img.architecture == "amd64") or ($img.os_arch == "amd64") then
                  "\n- **AMD64:** `" + $img.digest + "`"
                else
                  "\n- **" + ($img.architecture // "unknown") + ":** `" + $img.digest + "`"
                end')
              
              if [ "$SIZE" != "0" ] && [ "$SIZE" != "Unknown" ]; then
                SIZE_MB=$(echo "scale=2; $SIZE/1024/1024" | bc)
              else
                SIZE_MB="Unknown"
              fi
              
              echo "## ${image}:${VERSION}"
              echo ""
              echo "- **Description:** ${DESCRIPTION}"
              echo "- **Size:** ${SIZE_MB} MB"
              echo "- **Last Updated:** ${LAST_UPDATED}"
              echo ""
              echo "### Digests by Architecture"
              echo "${ARCHITECTURES}"
              echo ""
              echo "### Image References"
              echo "\`\`\`"
              echo "$TAG_INFO" | jq -r '.images[] | . as $img | 
                if ($img.architecture == "arm64") or ($img.os_arch == "arm64") then
                  "# ARM64\n" + "'${image}'" + "@" + $img.digest + "\n"
                elif ($img.architecture == "amd64") or ($img.os_arch == "amd64") then
                  "# AMD64\n" + "'${image}'" + "@" + $img.digest + "\n"
                else
                  "# " + ($img.architecture // "unknown") + "\n" + "'${image}'" + "@" + $img.digest + "\n"
                end'
              echo "\`\`\`"
              echo ""
              echo "View on [Docker Hub](https://hub.docker.com/r/${NAMESPACE}/${REPOSITORY}/tags?name=${VERSION})"
              echo ""
            done
            echo 'EOF'
          } >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
