name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'  # This will trigger the workflow for any tag that starts with v

jobs:
  build:
    runs-on: ubuntu-latest  # Lightweight OS for Docker builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest Amazon Linux 2023 tag update timestamp
        id: get_timestamp
        run: |
          echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t my-docker-image:${{ env.TIMESTAMP }} .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push my-docker-image:${{ env.TIMESTAMP }}
