name: Tag Docker Image as Latest

on:
  push:
    tags:
      - latest
  workflow_dispatch:
  
jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Get git tag name to put docker latest tag on it
        id: git_tag
        run: |
          ## Geting first v* tag on the same commit where latest tag is set   
          vtag=$(git ls-remote --tags https://github.com/$github_repository.git | awk -F'/' '/refs\/tags\/latest/{latest=$1} !/refs\/tags\/latest/{if($1==latest) {printf "%s", $NF; exit}}')
          
          if echo $vtag | grep -v '^v' > /dev/null; then 
            echo "Expected exactly one 'v*' tag, Exiting."
            exit 1
          fi

          echo "vtag=$vtag" >> $GITHUB_OUTPUT
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create latest tag
        run: |
          # get output of step id: get_tag named vtag
          TAG_NAME=${{ steps.get_tag.outputs.vtag }}
          # Assuming the tag is in the format v0.0.4
          docker buildx imagetools create \
            --tag gfish/devenv_amazonlinux_2023:latest \
            mydockerhubuser/myimage:${TAG_NAME}
