name: Tag Docker Image as Latest

on:
  push:
    tags:
      - latest
  workflow_dispatch:
  
jobs:
  tag-latest:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO: gfish/devenv_amazonlinux_2023

    steps:
      - name: Get git tag name to put docker latest tag on it
        id: get_tag
        run: |
          set -x
          ## Geting first v* tag on the same commit where latest tag is set   
          vtag=$(git ls-remote --tags https://github.com/${{ github.repository }}.git | awk -F'/' '/refs\/tags\/latest/{latest=$1} !/refs\/tags\/latest/{if($1==latest) {printf "%s", $NF; exit}}')
          
          if echo $vtag | grep -v '^v' > /dev/null; then 
            echo "Expected exactly one 'v*' tag, Exiting."
            exit 1
          fi
          echo "Found tag: ${vtag} where latest tag is"
          echo "vtag=$vtag" >> $GITHUB_OUTPUT
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create latest tag
        run: |
          # get output of step id: get_tag named vtag
          TAG_NAME="${{ steps.get_tag.outputs.vtag }}"
          echo "Taging dockerhub tag ${TAG_NAME} with latest tag"
          # Assuming the tag is in the format v0.0.4
          docker buildx imagetools create \
            --tag "${DOCKERHUB_REPO}:latest" \
            "${DOCKERHUB_REPO}:${TAG_NAME}"

      - name: Issue Docker Release
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: docker-releases.yml
          ref: ${{ github.ref }}
          inputs: |
            version: ${{ steps.get_tag.outputs.vtag }}
            docker_tags: ${{ env.DOCKERHUB_REPO }}
