name: Tag Docker Image as Latest

on:
  push:
    tags:
      - 'latest'  # Triggers when 'latest' tag is pushed

jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Docker Hub Credentials
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          # Authenticate and retrieve token
          token=$(curl -s -X POST "https://hub.docker.com/v2/users/login/" \
            -d "{\"username\": \"$DOCKERHUB_USERNAME\", \"password\": \"$DOCKERHUB_PASSWORD\"}" \
            -H "Content-Type: application/json" | jq -r .token)

          if [ -z "$token" ]; then
            echo "Authentication failed. Check Docker Hub credentials."
            exit 1
          fi

          # Set image name
          image_name="mydockerhubuser/myimage"  # Replace with your image repo
          
          # Get tags for the current commit
          v_tags=$(git tag --points-at HEAD | grep "^v[0-9]*\.[0-9]*\.[0-9]*$")

          # Check for exactly one matching version tag
          tag_count=$(echo "$v_tags" | wc -l)
          if [ "$tag_count" -ne 1 ]; then
            echo "Expected exactly one 'v*' tag, found $tag_count. Exiting."
            exit 0
          fi

          v_tag=$(echo "$v_tags" | head -n 1)

          # Retrieve digest for the specific version tag
          digest=$(curl -s -H "Authorization: JWT $token" \
            "https://hub.docker.com/v2/repositories/$image_name/tags/$v_tag/" | jq -r .images[0].digest)

          if [ -z "$digest" ] || [ "$digest" == "null" ]; then
            echo "Failed to retrieve digest for tag $v_tag."
            exit 1
          fi

          # Create or update 'latest' tag with the same digest
          curl -s -X POST "https://hub.docker.com/v2/repositories/$image_name/tags/" \
            -H "Authorization: JWT $token" \
            -H "Content-Type: application/json" \
            -d "{\"tag\": \"latest\", \"digest\": \"$digest\"}"
