name: Tag Docker Image as Latest

on:
  push:
    tags:
      - latest
  workflow_dispatch:
  
jobs:
  tag-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get git tag name to put docker latest tag on it
        id: git_tag
        run: |
          # Get tags for the current commit
          v_tags=$(git tag --points-at latest | grep "^v[0-9]*\.[0-9]*\.[0-9]*$")

          # Check for exactly one matching version tag
          tag_count=$(echo "$v_tags" | wc -l)
          if [ "$tag_count" -ne 1 ]; then
            echo "Expected exactly one 'v*' tag, found $tag_count. Exiting."
            exit 1
          fi

          v_tag=$(echo "$v_tags" | head -n 1)
          
          echo "vtag=$v_tag" >> $GITHUB_OUTPUT
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create latest tag
        run: |
          # get output of step id: get_tag named vtag
          TAG_NAME=${{ steps.get_tag.outputs.vtag }}
          # Assuming the tag is in the format v0.0.4
          docker buildx imagetools create \
            --tag gfish/devenv_amazonlinux_2023:latest \
            mydockerhubuser/myimage:${TAG_NAME}
